title: Mike Kot's blog
email: to-website@myrrc.dev

description: >-
  Mike Kot's blog about stuff, mostly music and software

url: "https://myrrc.dev"
date_format: "%b %-d, %Y"

liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

pagination:
  enabled: true
  per_page: 10
  trail: { before: 2, after: 2 }
  title: ':title | :num of :max'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    enabled: true
    layouts: [ autopage_tags.html ]
  categories: { enabled: false }
  collections: { enabled: false }

exclude:
  - Session.vim
  - build.sh
  - serve.sh
